//! # Data Models
//!
//! This module contains the core data structures used throughout the application.
//! These models represent the shape of data as it flows through the system,
//! from API responses to processed metrics.
//!
//! The models provide type-safe representations of complex data structures,
//! making it easier to work with and transform metrics data. They serve as
//! the foundation for both the service layer (which fetches and sends data)
//! and the processing layer (which transforms data).
//!
//! ## Submodules
//!
//! * `github` - Contains data structures for GitHub Copilot metrics.
//!   These models represent the metrics data as received from the GitHub API,
//!   including enterprise-wide and team-specific metrics for code completions,
//!   chat interactions, and pull request activities.
//!
//! Using these models ensures consistency in how data is represented across
//! different parts of the application and simplifies serialization/deserialization
//! when communicating with external APIs.

// Generated by Github Copilot
pub mod github;
// Generated Code by Github Copilot ends here
