// Generated by Github Copilot
mod handler;
mod models;
mod services;
#[cfg(test)]
mod tests;

use lambda_runtime::{run, service_fn, Error};
use tracing;

#[tokio::main]
async fn main() -> Result<(), Error> {
    // Load .env file in development
    #[cfg(debug_assertions)]
    {
        println!("Loading .env file for development");
        dotenvy::dotenv().ok();
    }

    // Initialize tracing
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        .with_target(false)
        .without_time()
        .init();

    // Run the lambda function
    run(service_fn(handler::function_handler)).await
}
